#!/usr/bin/env python3
import sys, subprocess
import settings

if len(sys.argv) <= 1:
    print('Please enter your command.')
    sys.exit()

command = sys.argv[1:]

if command == ['-s']:
    with open(settings.CWD + 'process.txt', 'r') as fin:
        content = [i.replace('\n', '') for i in fin.readlines()]
    
    if content:
        for i in content:
            print(i)
    else:
        print('No active jobs.')

else:
    process = subprocess.Popen(command)
    pid, name = process.pid, ' '.join(process.args)

    with open(settings.CWD + 'process.txt', 'a') as fin:
        fin.write('{} {}\n'.format(pid, name))
